#!/bin/bash
# Install (or re-install) the launchd agents for the Marathon Training app:
#
#   com.marathon.app     — keeps the API+frontend server running on :8000
#   com.marathon.backup  — daily DB snapshot to iCloud Drive (noon + at login)
#
# launchd plists require absolute paths, so instead of committing plists with
# a hardcoded username/repo path, this script GENERATES them for this machine
# (from its own location and `command -v uv`), installs them to
# ~/Library/LaunchAgents, and loads them.
#
# Idempotent — safe to re-run to apply plist changes or after moving the repo.
# Loading the backup agent also snapshots the DB immediately (RunAtLoad).
#
# The Apache reverse proxy is installed separately (needs sudo):
#   sudo cp deploy/marathon.apache.conf /etc/apache2/other/marathon.conf
#   sudo apachectl configtest && sudo apachectl restart
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
AGENTS_DIR="$HOME/Library/LaunchAgents"

UV_BIN="$(command -v uv || true)"
if [ -z "$UV_BIN" ]; then
  echo "ERROR: uv not found on PATH — install it first: https://docs.astral.sh/uv/" >&2
  exit 1
fi

mkdir -p "$AGENTS_DIR"

# Write the plist from stdin, replacing (and unloading) any existing copy.
install_agent() {
  local label="$1" plist="$AGENTS_DIR/$1.plist"
  if [ -f "$plist" ]; then
    launchctl unload "$plist" 2>/dev/null || true
  fi
  cat > "$plist"
  launchctl load -w "$plist"
  echo "  loaded $label"
}

echo "Installing launchd agents (repo: $REPO_DIR)..."

install_agent com.marathon.app <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <!-- Generated by deploy/install.sh — re-run that script to regenerate.
         Runs uvicorn directly (not serve.sh) so it does NOT rebuild the
         frontend on every boot; rebuild manually with \`npm run build\`. -->
    <key>Label</key>
    <string>com.marathon.app</string>

    <key>ProgramArguments</key>
    <array>
        <string>$UV_BIN</string>
        <string>run</string>
        <string>uvicorn</string>
        <string>app.main:app</string>
        <string>--host</string>
        <string>0.0.0.0</string>
        <string>--port</string>
        <string>8000</string>
        <string>--log-config</string>
        <string>$REPO_DIR/backend/log_config.json</string>
    </array>

    <key>WorkingDirectory</key>
    <string>$REPO_DIR/backend</string>

    <!-- Start at login and restart if it ever exits or crashes. -->
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>

    <key>StandardOutPath</key>
    <string>$REPO_DIR/marathon.app.log</string>
    <key>StandardErrorPath</key>
    <string>$REPO_DIR/marathon.app.log</string>
</dict>
</plist>
EOF

install_agent com.marathon.backup <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <!-- Generated by deploy/install.sh — re-run that script to regenerate.
         Run-and-exit job (no KeepAlive): fires once at load, then daily at
         noon. If the Mac is asleep at noon, launchd runs it on next wake. -->
    <key>Label</key>
    <string>com.marathon.backup</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$REPO_DIR/deploy/backup_db.sh</string>
    </array>

    <!-- Run once when loaded (so the first snapshot happens immediately)... -->
    <key>RunAtLoad</key>
    <true/>
    <!-- ...and every day at 12:00. -->
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>12</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>

    <key>StandardOutPath</key>
    <string>$REPO_DIR/marathon.backup.log</string>
    <key>StandardErrorPath</key>
    <string>$REPO_DIR/marathon.backup.log</string>
</dict>
</plist>
EOF

echo "Done. App on http://127.0.0.1:8000 — verify with ./status.sh"
